language: rust
rust:
- stable
notifications:
  slack:
    secure: Clis/gOZzMGTxTe4tSntqWWArBDkItJPyBZSSsPhdn17Gm7l+ozTB76EOQsB8D8UKQrRRFO0Y+9Xr/fKk8h1bAPKcDzq6BwcwJRbURDOiNtKCxGpBurYGnX5gCbN3I0i3uhAgXlhgwcEw5jlzi32djBNAmvsrku+H8qAPTQVwGjNNA0W5tCeU8GCb5GxtZZf5fPF2uVUlePSvpqmkCfRdBuwmC9XPSvIVpXTI648AUnuqaqxJNFbDAkgDXEy/ViXvg/vuFt7olZ5NvcWNSKwJYaTiw24K+X89MN2B2hjhrjXWOZ0By3+w9JRQjOkM02SqkRWjkaecgQvGykxgaE38Zg9IGGLx2BIlPVhka4fOGQjmntI70mfN86msx2efOe/crrHBlLy/p75lHSlGNj7cK4YZyYWNjogsyAsYlsr/f4WnKhEvFyHml/pEvxWmgeoRjlz2EggjHMMh4mihTcVybhFaVDbxPwEA0kFagMBkZ5uHowjskJmRdRY/oOTpNUxVT140FnqTZ13+BZYiZF9zUqy/Av8bqjXBsSurUpXKrd3QEewl3ScOT5a/1H6yF+d64eQLJqkNuihk5mtLnKaJc5bfpieIs7gyjkaGrJ2o5uekum6r7lxh4IllChUR3VqL2/5z5tpWKE75ms9PSvFX0maA6D4NaYIHT7M3O8j+zE=
